### ISSUE TITLE
Create authorList in authors.js

### ISSUE THREAD

**Issue by Jubjub422** [Jubjub422/Team-1-Beys-Blog#2]
Create an authorList function that returns an html representation of the authors to be displayed on the browser.

**Comment by Jubjub422** [comment]
YES PLEASE

**Comment by SamuelTrevan** [comment]
Hey Ross one more question on this. Do you want the authors displayed in an unordered list or an ordered list?

**Comment by Jubjub422** [comment]
Unordered list, refer to directions as well to see how they need to be positioned.

**Comment by SamuelTrevan** [comment]
This has been completed
